language: generic

services:
  - docker

jobs:
  include:
    - stage: build-and-test
      name: Build and Test
      script:
        - scripts/build-and-run.sh
      after_success: 
        - docker-compose -f docker-compose.yml up --abort-on-container-exit


# deploy:
#   provider: elasticbeanstalk
#   region: 'us-west-2'
#   app: 'workbound-api'
#   env: 'Workboundapi-env'
#   bucket_name: 'elasticbeanstalk-us-west-2-090674468459'
#   bucket_path: 'workbound-api'
#   on:
#     branch: main
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY