language: generic

services:
  - docker'

script:
  - docker-compose run --entrypoint="python manage.py test" app

after_script:
  - docker-compose down

# deploy:
#   provider: elasticbeanstalk
#   region: 'us-west-2'
#   app: 'workbound-api'
#   env: 'Workboundapi-env'
#   bucket_name: 'elasticbeanstalk-us-west-2-090674468459'
#   bucket_path: 'workbound-api'
#   on:
#     branch: main
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY
