language: python
python:  
  - "3.7"
# command to install dependencies

install:
  - pip install -r requirements.txt

services:
  - docker

script:
  - docker-compose -f ./docker-compose.dev.yml --env-file ./app/.env run app sh -c "python manage.py wait_for_db && python manage.py test && flake8"

deploy:
  provider: elasticbeanstalk
  region: 'us-west-2'
  app: 'workbound-api'
  env: 'Workboundapi-env'
  bucket_name: 'elasticbeanstalk-us-west-2-090674468459'
  bucket_path: 'workbound-api'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
