language: generic

services:
  - docker'

before_install:
  - docker-compose up -d --build

script:
  - docker-compose exec app python manage.py test
  - docker-compose exec app flake8

# deploy:
#   provider: elasticbeanstalk
#   region: 'us-west-2'
#   app: 'workbound-api'
#   env: 'Workboundapi-env'
#   bucket_name: 'elasticbeanstalk-us-west-2-090674468459'
#   bucket_path: 'workbound-api'
#   on:
#     branch: main
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY