version: "3"

services:
    nginx:
        build: ./nginx
        restart: always
        ports:
          - 80:80
        depends_on:
          - app
    app:
        build: 
            context: .
        restart: always
        expose:
            - 8000
        volumes: 
            - ./app:/app
        command: >
            sh -c "python manage.py init_admin &&
                   gunicorn app.wsgi:application --bind 0.0.0.0:8000"
        environment: 
            - SECRET_KEY
            - RDS_HOSTNAME
            - RDS_PORT
            - RDS_DB_NAME
            - RDS_USERNAME
            - RDS_PASSWORD
            - FIREBASE_CONFIG
            - DJANGO_SUPERUSER_EMAIL
            - DJANGO_SUPERUSER_PASSWORD
