version: "3.3"

services:
    # nginx:
    #     build: ./nginx
    #     restart: always
    #     ports:
    #         - 8000:8000
    #     depends_on:
    #         - app
    #     volumes:
    #         - ./app/static:/app/static
    app:
        build: 
            context: .
        ports:
            - 8000:8000
        volumes: 
            - ./app/static:/app/static
            - ./app:/app
        environment: 
            - SECRET_KEY
            - DB_HOST=db
            - DB_NAME=app
            - DB_USER=postgres
            - POSTGRES_PASSWORD
            - FIREBASE_PROJECT_ID
            - FIREBASE_PRIVATE_KEY_ID
            - FIREBASE_PRIVATE_KEY
            - FIREBASE_CLIENT_ID
            - DJANGO_SUPERUSER_EMAIL
            - DJANGO_SUPERUSER_PASSWORD
            - RECAPTCHA_SECRET_KEY
        depends_on: 
            - db
    db:
        image: postgres:13-alpine
        environment: 
            - POSTGRES_DB=app
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD
