version: "3.3"

services:
    nginx:
        build: ./nginx
        restart: always
        ports:
            - 8000:8000
        depends_on:
            - app
        volumes:
            - ./app/static:/app/static
            - ./app/media:/app/media
    app:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        command: bash -c "
            python manage.py wait_for_db &&
            python manage.py migrate --noinput &&
            python manage.py collectstatic --noinput &&
            python manage.py init_admin &&
            gunicorn app.wsgi:application --bind 0.0.0.0:8000"
            # python manage.py runserver 0.0.0.0:8000"
        # ports:
        #     - 8000:8000
        volumes: 
            - ./app/media:/app/media
            - ./app/static:/app/static
            - ./app:/app
        environment: 
            - SECRET_KEY
            - DB_HOST=db
            - DB_NAME=app
            - DB_USER=postgres
            - POSTGRES_PASSWORD
            - FIREBASE_PROJECT_ID
            - FIREBASE_PRIVATE_KEY_ID
            - FIREBASE_PRIVATE_KEY
            - FIREBASE_CLIENT_ID
            - DJANGO_SUPERUSER_EMAIL
            - DJANGO_SUPERUSER_PASSWORD
            - RECAPTCHA_SECRET_KEY
            - SMTP_USERNAME
            - SMTP_PASSWORD
            - SMTP_PORT
            - SMTP_HOST
        depends_on: 
            - db
    db:
        image: postgres:13-alpine
        environment: 
            - POSTGRES_DB=app
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD
