version: "3"

services:
    app:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "8000:8000"
        volumes: 
            - ./app:/app
        command: >
            sh -c "python manage.py wait_for_db &&
                   python manage.py makemigrations &&
                   python manage.py migrate --noinput &&
                   python manage.py collectstatic --noinput &&
                   python manage.py init_admin &&
                   python manage.py runserver 0.0.0.0:8000"
        environment: 
            - SECRET_KEY
            - DB_HOST=db
            - DB_NAME=app
            - DB_USER=postgres
            - POSTGRES_PASSWORD
            - FIREBASE_CONFIG
            - DJANGO_SUPERUSER_EMAIL
            - DJANGO_SUPERUSER_PASSWORD
            - DEBUG
        depends_on: 
            - db
    
    db:
        image: postgres:13-alpine
        restart: always
        environment: 
            - POSTGRES_DB=app
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD