# Generated by Django 3.2.3 on 2021-05-18 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', 'add_role_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roletype',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
