# Generated by Django 3.2.3 on 2021-05-19 02:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0004_auto_20210518_1416'),
        ('user', '0001_alter_roletype_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('user', 'category', 'role_type')},
        ),
    ]
