# Generated by Django 3.2.5 on 2021-07-29 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['id'], 'verbose_name': 'Portfolio', 'verbose_name_plural': 'Portfolios'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['order'], 'verbose_name': 'Section', 'verbose_name_plural': 'Sections'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['title'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AlterModelOptions(
            name='workitem',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Work Item', 'verbose_name_plural': 'Work Items'},
        ),
        migrations.AddField(
            model_name='section',
            name='order',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='completion_days',
            field=models.PositiveSmallIntegerField(default=7, help_text='Expected days to complete a WorkItem with this task'),
        ),
        migrations.AddField(
            model_name='workitem',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assigned_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workitem',
            name='expected_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workitem',
            name='order',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
