# Generated by Django 3.2.3 on 2021-06-06 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_workitem_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completion_days',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Expected days to complete                                                        a WorkItem with this task', null=True),
        ),
    ]
