# Generated by Django 3.2.3 on 2021-05-20 21:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20210520_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='duration',
            field=models.PositiveSmallIntegerField(default=1, help_text='Typical duration of this task'),
            preserve_default=False,
        ),
    ]
