# Generated by Django 3.2.3 on 2021-05-18 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20210518_1309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='user',
            new_name='created_by',
        ),
    ]
