# Generated by Django 3.2.3 on 2021-05-20 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_task_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='archived',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sectioncategory',
            name='archived',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
