# Generated by Django 3.2.3 on 2021-05-18 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_rename_user_portfolio_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='meta',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sections', to='portfolio.portfolio'),
        ),
    ]
