# Generated by Django 3.2.3 on 2021-06-07 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_task_completion_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='expected_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
