# Generated by Django 3.2.3 on 2021-05-20 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0004_auto_20210520_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workitem_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('completed', models.DateTimeField(blank=True, editable=False, null=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='workitems', to='portfolio.section')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='portfolio.sectioncategory')),
            ],
        ),
    ]
