# Generated by Django 3.2.3 on 2021-06-07 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_workitem_expected_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='order',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='workitem',
            name='order',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
