# Generated by Django 3.2.3 on 2021-05-21 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_portfolio_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name': 'Portfolio', 'verbose_name_plural': 'Portfolios'},
        ),
    ]
