# Generated by Django 3.2.3 on 2021-05-21 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_portfolio_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sectioncategory',
            options={'verbose_name': 'Section Category', 'verbose_name_plural': 'Section Categories'},
        ),
    ]
