# Generated by Django 3.2.3 on 2021-05-21 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_sectioncategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'Section', 'verbose_name_plural': 'Sections'},
        ),
    ]
