# Generated by Django 3.2.3 on 2021-05-21 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_alter_section_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workitem',
            options={'verbose_name': 'Work Item', 'verbose_name_plural': 'Work Items'},
        ),
    ]
